"""Gameplay tuning constants (movement, combat, spawning)."""

PROJECTILE_SPEED = 7.5
PROJECTILE_MAX_DISTANCE = 18.0
PROJECTILE_COOLDOWN = 0.25
PROJECTILE_STEP_DISTANCE = 0.08
EXPLOSION_DURATION = 0.55

DASH_DISTANCE = 1.7
DASH_COOLDOWN = 0.65
DASH_STEP_DISTANCE = 0.12

ENEMY_SPAWN_INTERVAL = 4.0
ENEMY_SPAWN_DISTANCE = 2.5
ENEMY_SPAWN_ATTEMPTS = 32
ENEMY_MAX_COUNT = 12
ENEMY_HIT_RADIUS = 0.45
ENEMY_MIN_SEPARATION = 1.0

PLAYER_MAX_HEALTH = 100
PLAYER_HIT_RADIUS = 0.35
ENEMY_PROJECTILE_DAMAGE = 20

ENEMY_MOVE_SPEED = 2.4
ENEMY_STOP_DISTANCE = 1.15
ENEMY_FIRE_DISTANCE = 7.0
ENEMY_FIRE_COOLDOWN = 2.4
ENEMY_PROJECTILE_SPEED = 6.5
